name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle jib:build

#环境变量
env:
  #仓库用户
  CONTAINER_REPO_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  #仓库密码
  CONTAINER_REPO_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #mvn_deploy,mvn_install,gradle编译工具
  BUILD_TOOL: gradle


